---
- name: Apt-get update
  apt: name="software-properties-common" state=present cache_valid_time=43200
  tags:
    - packages
  when: ansible_os_family == "Debian"

- name: install packages for cloning
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - mercurial

####  --- customizations ------

- include: plugins.yml
  tags:
    - plugins
