---
# handlers file for redmine-ansible

- name: restart apache
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes
